import React from 'react'
import './workouts.css'

let workouts = [
    // =============================
    // BEGINNER LEVEL (50 workouts)
    // =============================
    { id: 1, name: "Wall Push-ups", reps: 12, sets: 3, category: "chest", level: "beginner" },
    { id: 2, name: "Bodyweight Squats", reps: 15, sets: 3, category: "legs", level: "beginner" },
    { id: 3, name: "Standing Lunges", reps: 8, sets: 2, category: "legs", level: "beginner" },
    { id: 4, name: "Knee Plank", reps: 30, sets: 3, category: "abs", level: "beginner" },
    { id: 5, name: "Basic Crunches", reps: 15, sets: 3, category: "abs", level: "beginner" },
    { id: 6, name: "Assisted Pull-ups (Band)", reps: 8, sets: 3, category: "back", level: "beginner" },
    { id: 7, name: "Dumbbell Bench Press (Light)", reps: 12, sets: 3, category: "chest", level: "beginner" },
    { id: 8, name: "Roman Chair Back Extensions", reps: 12, sets: 3, category: "back", level: "beginner" },
    { id: 9, name: "Seated Dumbbell Shoulder Press (Light)", reps: 12, sets: 3, category: "shoulders", level: "beginner" },
    { id: 10, name: "Bicep Curls (Light Dumbbells)", reps: 12, sets: 3, category: "arms", level: "beginner" },
    { id: 11, name: "Tricep Kickbacks (Light)", reps: 12, sets: 3, category: "arms", level: "beginner" },
    { id: 12, name: "Leg Raises (Bent Knees)", reps: 12, sets: 3, category: "abs", level: "beginner" },
    { id: 13, name: "Marching in Place", reps: 60, sets: 3, category: "cardio", level: "beginner" },
    { id: 14, name: "Step Touches", reps: 30, sets: 3, category: "cardio", level: "beginner" },
    { id: 15, name: "Seated Rows (Machine)", reps: 12, sets: 3, category: "back", level: "beginner" },
    { id: 16, name: "Lateral Raises (Very Light)", reps: 15, sets: 3, category: "shoulders", level: "beginner" },
    { id: 17, name: "Heel Raises (Standing)", reps: 20, sets: 3, category: "legs", level: "beginner" },
    { id: 18, name: "Dead Bug", reps: 12, sets: 3, category: "abs", level: "beginner" },
    { id: 19, name: "Fast Marching", reps: 45, sets: 3, category: "cardio", level: "beginner" },
    { id: 20, name: "Incline Push-ups", reps: 10, sets: 3, category: "chest", level: "beginner" },
    { id: 21, name: "Glute Bridges", reps: 15, sets: 3, category: "legs", level: "beginner" },
    { id: 22, name: "Superman Hold", reps: 20, sets: 3, category: "back", level: "beginner" },
    { id: 23, name: "Front Raises (Light)", reps: 12, sets: 3, category: "shoulders", level: "beginner" },
    { id: 24, name: "Hammer Curls (Light)", reps: 12, sets: 3, category: "arms", level: "beginner" },
    { id: 25, name: "Flutter Kicks (Short Range)", reps: 20, sets: 3, category: "abs", level: "beginner" },
    { id: 26, name: "Brisk Walking", reps: 90, sets: 1, category: "cardio", level: "beginner" },
    { id: 27, name: "Chest Flyes (Machine)", reps: 12, sets: 3, category: "chest", level: "beginner" },
    { id: 28, name: "Lat Pulldown (Light)", reps: 12, sets: 3, category: "back", level: "beginner" },
    { id: 29, name: "Shrugs (Light Dumbbells)", reps: 15, sets: 3, category: "shoulders", level: "beginner" },
    { id: 30, name: "Concentration Curl (Supported)", reps: 10, sets: 3, category: "arms", level: "beginner" },
    { id: 31, name: "Toe Taps", reps: 20, sets: 3, category: "abs", level: "beginner" },
    { id: 32, name: "Jumping Jacks (Slow)", reps: 20, sets: 3, category: "cardio", level: "beginner" },
    { id: 33, name: "Chair Squats", reps: 15, sets: 3, category: "legs", level: "beginner" },
    { id: 34, name: "Push-up (Knees)", reps: 8, sets: 3, category: "chest", level: "beginner" },
    { id: 35, name: "Bird-Dog", reps: 10, sets: 3, category: "back", level: "beginner" },
    { id: 36, name: "Shoulder Tap (From Knees)", reps: 10, sets: 3, category: "core", level: "beginner" },
    { id: 37, name: "Arm Circles", reps: 30, sets: 2, category: "shoulders", level: "beginner" },
    { id: 38, name: "Wrist Curls", reps: 15, sets: 3, category: "arms", level: "beginner" },
    { id: 39, name: "Ankle Circles + March", reps: 60, sets: 2, category: "cardio", level: "beginner" },
    { id: 40, name: "Standing Side Bends", reps: 15, sets: 3, category: "abs", level: "beginner" },
    { id: 41, name: "Wall Angels", reps: 12, sets: 3, category: "shoulders", level: "beginner" },
    { id: 42, name: "Palms-Up Wrist Curls", reps: 15, sets: 3, category: "arms", level: "beginner" },
    { id: 43, name: "Seated Leg Lifts", reps: 12, sets: 3, category: "legs", level: "beginner" },
    { id: 44, name: "Standing Oblique Crunches", reps: 15, sets: 3, category: "abs", level: "beginner" },
    { id: 45, name: "Low-Impact Aerobics", reps: 60, sets: 3, category: "cardio", level: "beginner" },
    { id: 46, name: "Floor Press (Light Dumbbells)", reps: 12, sets: 3, category: "chest", level: "beginner" },
    { id: 47, name: "Cat-Cow Stretch (Controlled)", reps: 12, sets: 2, category: "back", level: "beginner" },
    { id: 48, name: "Side-Lying Leg Lifts", reps: 12, sets: 3, category: "legs", level: "beginner" },
    { id: 49, name: "Neck Stretches (Isometric)", reps: 10, sets: 2, category: "shoulders", level: "beginner" },
    { id: 50, name: "Seated Punches", reps: 30, sets: 3, category: "cardio", level: "beginner" },

    // =============================
    // INTERMEDIATE LEVEL (50 workouts)
    // =============================
    { id: 51, name: "Standard Push-ups", reps: 12, sets: 4, category: "chest", level: "intermediate" },
    { id: 52, name: "Goblet Squats", reps: 12, sets: 4, category: "legs", level: "intermediate" },
    { id: 53, name: "Walking Lunges", reps: 10, sets: 3, category: "legs", level: "intermediate" },
    { id: 54, name: "Plank", reps: 60, sets: 3, category: "abs", level: "intermediate" },
    { id: 55, name: "Hanging Knee Raises", reps: 12, sets: 3, category: "abs", level: "intermediate" },
    { id: 56, name: "Pull-ups", reps: 8, sets: 3, category: "back", level: "intermediate" },
    { id: 57, name: "Barbell Bench Press", reps: 10, sets: 4, category: "chest", level: "intermediate" },
    { id: 58, name: "Deadlifts", reps: 8, sets: 3, category: "back", level: "intermediate" },
    { id: 59, name: "Overhead Dumbbell Press", reps: 10, sets: 3, category: "shoulders", level: "intermediate" },
    { id: 60, name: "Barbell Bicep Curls", reps: 10, sets: 3, category: "arms", level: "intermediate" },
    { id: 61, name: "Dips (Bodyweight)", reps: 10, sets: 3, category: "arms", level: "intermediate" },
    { id: 62, name: "Hanging Leg Raises", reps: 10, sets: 3, category: "abs", level: "intermediate" },
    { id: 63, name: "Jump Rope", reps: 60, sets: 4, category: "cardio", level: "intermediate" },
    { id: 64, name: "Burpees", reps: 12, sets: 3, category: "cardio", level: "intermediate" },
    { id: 65, name: "Pendlay Rows", reps: 10, sets: 3, category: "back", level: "intermediate" },
    { id: 66, name: "Lateral Raises (Moderate Weight)", reps: 12, sets: 4, category: "shoulders", level: "intermediate" },
    { id: 67, name: "Calf Raises (Weighted)", reps: 15, sets: 4, category: "legs", level: "intermediate" },
    { id: 68, name: "Russian Twists (Weighted)", reps: 20, sets: 3, category: "abs", level: "intermediate" },
    { id: 69, name: "Mountain Climbers", reps: 40, sets: 4, category: "cardio", level: "intermediate" },
    { id: 70, name: "Incline Dumbbell Press", reps: 10, sets: 3, category: "chest", level: "intermediate" },
    { id: 71, name: "Lat Pulldowns (Wide Grip)", reps: 12, sets: 3, category: "back", level: "intermediate" },
    { id: 72, name: "Arnold Press", reps: 10, sets: 3, category: "shoulders", level: "intermediate" },
    { id: 73, name: "Hamstring Curls (Machine)", reps: 12, sets: 3, category: "legs", level: "intermediate" },
    { id: 74, name: "Close-Grip Bench Press", reps: 10, sets: 3, category: "arms", level: "intermediate" },
    { id: 75, name: "Bicycle Crunches", reps: 25, sets: 3, category: "abs", level: "intermediate" },
    { id: 76, name: "High Knees", reps: 50, sets: 4, category: "cardio", level: "intermediate" },
    { id: 77, name: "Decline Push-ups", reps: 10, sets: 3, category: "chest", level: "intermediate" },
    { id: 78, name: "Front Squats", reps: 10, sets: 4, category: "legs", level: "intermediate" },
    { id: 79, name: "T-Bar Rows", reps: 10, sets: 3, category: "back", level: "intermediate" },
    { id: 80, name: "Face Pulls (Ropes)", reps: 15, sets: 4, category: "shoulders", level: "intermediate" },
    { id: 81, name: "Zottman Curls", reps: 10, sets: 3, category: "arms", level: "intermediate" },
    { id: 82, name: "Reverse Crunches", reps: 15, sets: 3, category: "abs", level: "intermediate" },
    { id: 83, name: "Jump Squats", reps: 15, sets: 3, category: "cardio", level: "intermediate" },
    { id: 84, name: "Cable Chest Flyes", reps: 12, sets: 3, category: "chest", level: "intermediate" },
    { id: 85, name: "Single-Arm Dumbbell Row", reps: 10, sets: 3, category: "back", level: "intermediate" },
    { id: 86, name: "Upright Rows", reps: 10, sets: 3, category: "shoulders", level: "intermediate" },
    { id: 87, name: "Tricep Dips (Between Benches)", reps: 12, sets: 3, category: "arms", level: "intermediate" },
    { id: 88, name: "Side Plank (Each Side)", reps: 30, sets: 3, category: "abs", level: "intermediate" },
    { id: 89, name: "Stair Climbing", reps: 90, sets: 3, category: "cardio", level: "intermediate" },
    { id: 90, name: "Bulgarian Split Squats", reps: 8, sets: 3, category: "legs", level: "intermediate" },
    { id: 91, name: "Skull Crushers", reps: 10, sets: 3, category: "arms", level: "intermediate" },
    { id: 92, name: "Cable Woodchoppers", reps: 12, sets: 3, category: "abs", level: "intermediate" },
    { id: 93, name: "Battle Ropes (30s)", reps: 30, sets: 4, category: "cardio", level: "intermediate" },
    { id: 94, name: "Incline Dumbbell Flyes", reps: 12, sets: 3, category: "chest", level: "intermediate" },
    { id: 95, name: "Shrugs (Barbell)", reps: 12, sets: 4, category: "shoulders", level: "intermediate" },
    { id: 96, name: "Leg Press", reps: 15, sets: 4, category: "legs", level: "intermediate" },
    { id: 97, name: "Preacher Curls", reps: 10, sets: 3, category: "arms", level: "intermediate" },
    { id: 98, name: "V-Ups", reps: 15, sets: 3, category: "abs", level: "intermediate" },
    { id: 99, name: "Sprints (30m)", reps: 6, sets: 1, category: "cardio", level: "intermediate" },
    { id: 100, name: "Dumbbell Pullover", reps: 12, sets: 3, category: "chest", level: "intermediate" },

    // =============================
    // EXPERT LEVEL (50 workouts)
    // =============================
    { id: 101, name: "Plyometric Push-ups", reps: 10, sets: 4, category: "chest", level: "expert" },
    { id: 102, name: "Barbell Back Squats", reps: 8, sets: 5, category: "legs", level: "expert" },
    { id: 103, name: "Jumping Lunges", reps: 12, sets: 4, category: "legs", level: "expert" },
    { id: 104, name: "Dragon Flag Progression", reps: 6, sets: 3, category: "abs", level: "expert" },
    { id: 105, name: "Hanging Leg Raise to Toes-to-Bar", reps: 10, sets: 4, category: "abs", level: "expert" },
    { id: 106, name: "Weighted Pull-ups", reps: 6, sets: 4, category: "back", level: "expert" },
    { id: 107, name: "Weighted Bench Press", reps: 6, sets: 5, category: "chest", level: "expert" },
    { id: 108, name: "Sumo Deadlifts", reps: 5, sets: 4, category: "back", level: "expert" },
    { id: 109, name: "Standing Overhead Press (Barbell)", reps: 6, sets: 4, category: "shoulders", level: "expert" },
    { id: 110, name: "Heavy Barbell Curls", reps: 6, sets: 4, category: "arms", level: "expert" },
    { id: 111, name: "Weighted Dips", reps: 8, sets: 4, category: "arms", level: "expert" },
    { id: 112, name: "Ab Wheel Rollouts (From Feet)", reps: 10, sets: 4, category: "abs", level: "expert" },
    { id: 113, name: "Double-Under Jump Rope", reps: 50, sets: 4, category: "cardio", level: "expert" },
    { id: 114, name: "Burpee Pull-ups", reps: 10, sets: 4, category: "cardio", level: "expert" },
    { id: 115, name: "Weighted Chin-ups", reps: 6, sets: 4, category: "back", level: "expert" },
    { id: 116, name: "Power Cleans", reps: 5, sets: 4, category: "shoulders", level: "expert" },
    { id: 117, name: "Box Jumps (30+ inches)", reps: 10, sets: 4, category: "legs", level: "expert" },
    { id: 118, name: "Windshield Wipers", reps: 10, sets: 3, category: "abs", level: "expert" },
    { id: 119, name: "Sled Push", reps: 40, sets: 4, category: "cardio", level: "expert" },
    { id: 120, name: "Explosive Push Press", reps: 6, sets: 4, category: "shoulders", level: "expert" },
    { id: 121, name: "Incline Bench Press (Heavy)", reps: 6, sets: 4, category: "chest", level: "expert" },
    { id: 122, name: "Front Squat (Olympic)", reps: 6, sets: 4, category: "legs", level: "expert" },
    { id: 123, name: "Renegade Rows", reps: 10, sets: 3, category: "back", level: "expert" },
    { id: 124, name: "Handstand Push-up (Wall-Assisted)", reps: 8, sets: 3, category: "shoulders", level: "expert" },
    { id: 125, name: "Spider Curls", reps: 8, sets: 4, category: "arms", level: "expert" },
    { id: 126, name: "L-Sit Hold", reps: 20, sets: 3, category: "abs", level: "expert" },
    { id: 127, name: "Suicide Sprints", reps: 5, sets: 1, category: "cardio", level: "expert" },
    { id: 128, name: "Ring Dips", reps: 10, sets: 4, category: "chest", level: "expert" },
    { id: 129, name: "Deficit Deadlifts", reps: 5, sets: 4, category: "back", level: "expert" },
    { id: 130, name: "Snatch Grip High Pulls", reps: 8, sets: 3, category: "shoulders", level: "expert" },
    { id: 131, name: "Zercher Squats", reps: 8, sets: 4, category: "legs", level: "expert" },
    { id: 132, name: "JM Press", reps: 8, sets: 4, category: "arms", level: "expert" },
    { id: 133, name: "Hanging Windshield Wipers", reps: 8, sets: 3, category: "abs", level: "expert" },
    { id: 134, name: "HIIT (30s On/30s Off)", reps: 8, sets: 1, category: "cardio", level: "expert" },
    { id: 135, name: "One-Arm Push-ups (Assisted)", reps: 6, sets: 3, category: "chest", level: "expert" },
    { id: 136, name: "Hack Squats (Heavy)", reps: 8, sets: 4, category: "legs", level: "expert" },
    { id: 137, name: "One-Arm Lat Pulldown", reps: 8, sets: 3, category: "back", level: "expert" },
    { id: 138, name: "Muscle-Ups", reps: 5, sets: 4, category: "shoulders", level: "expert" },
    { id: 139, name: "Concentration Curls (Heavy)", reps: 8, sets: 4, category: "arms", level: "expert" },
    { id: 140, name: "Toes-to-Bar Knees-to-Elbows", reps: 12, sets: 4, category: "abs", level: "expert" },
    { id: 141, name: "Sandbag Runs", reps: 40, sets: 4, category: "cardio", level: "expert" },
    { id: 142, name: "Ring Push-ups (Feet Elevated)", reps: 10, sets: 4, category: "chest", level: "expert" },
    { id: 143, name: "Pistol Squats", reps: 6, sets: 3, category: "legs", level: "expert" },
    { id: 144, name: "Farmer's Carry (Heavy)", reps: 50, sets: 4, category: "back", level: "expert" },
    { id: 145, name: "Turkish Get-Up", reps: 5, sets: 3, category: "shoulders", level: "expert" },
    { id: 146, name: "Overhead Tricep Extension (Barbell)", reps: 8, sets: 4, category: "arms", level: "expert" },
    { id: 147, name: "Human Flag Progression", reps: 5, sets: 3, category: "abs", level: "expert" },
    { id: 148, name: "Rowing Machine (Intense)", reps: 500, sets: 1, category: "cardio", level: "expert" },
    { id: 149, name: "Clap Push-ups", reps: 8, sets: 4, category: "chest", level: "expert" },
    { id: 150, name: "Atlas Stone Lifts", reps: 5, sets: 3, category: "legs", level: "expert" }
];

export default function Workouts({ level, type1, setSelectedWorkouts, day }) {
    const filteredWorkouts = workouts.filter((workout) => workout.level === level && (workout.category === type1));
    return (
        <div className='workouts'>
            {filteredWorkouts.map((workout) => (
                <div key={workout.id} className="workout">
                    <h1>{workout.name}</h1>
                    <p>Reps: {workout.reps}</p>
                    <p>Sets: {workout.sets}</p>
                    <p>Category: {workout.category}</p>
                    <button onClick={() => setSelectedWorkouts((prev) => ({ ...prev, [day]: { workouts: [...prev[day].workouts, workout] } }))}>Add to Plan</button>
                </div>
            ))}
        </div>
    )
}